Repository LO-CO-CO/LOCOCO-SERVER, pull requests merged in 2025-08, with the labels that each got.

#171 [REFACTOR] #171 : 메인페이지 신상품 조회의 정렬 조건 변경
  src/main/java/com/lokoko/domain/product/domain/repository/ProductRepositoryImpl.java
Labels: 🔨 Refactor

#175 [CHORE] #175 jira 깃허브 연동
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/issue-form.yml
  .github/ISSUE_TEMPLATE/refactor.md
  .github/workflows/close-jira-issue.yml
  .github/workflows/create-jira-issue.yml
Labels: ⚙ Setting, ✨ Feature

#192 [DOCS] LCO-8 ProductController 에서 스웨거 형식 수정
  src/main/java/com/lokoko/domain/product/api/ProductController.java
  src/main/java/com/lokoko/domain/product/api/dto/response/ProductsByCategoryResponse.java
Labels: 📋 DOCS
