Repository LO-CO-CO/LOCOCO-SERVER, pull requests merged in 2025-09, with the labels that each got.

#204 [FEAT] #204 캠페인 및 연관 도메인 세팅
  src/main/java/com/lokoko/domain/brand/domain/entity/Brand.java
  src/main/java/com/lokoko/domain/campaign/api/CampaignController.java
  src/main/java/com/lokoko/domain/campaign/api/message/ResponseMessage.java
  src/main/java/com/lokoko/domain/campaign/application/service/CampaignReadService.java
  src/main/java/com/lokoko/domain/campaign/application/service/CampaignService.java
  src/main/java/com/lokoko/domain/campaign/application/service/CampaignStatusManager.java
  src/main/java/com/lokoko/domain/campaign/domain/entity/Campaign.java
  src/main/java/com/lokoko/domain/campaign/domain/entity/CreatorCampaign.java
  src/main/java/com/lokoko/domain/campaign/domain/entity/enums/CampaignStatus.java
  src/main/java/com/lokoko/domain/campaign/domain/entity/enums/CampaignType.java
  src/main/java/com/lokoko/domain/campaign/domain/entity/enums/ParticipationStatus.java
  src/main/java/com/lokoko/domain/campaign/domain/repository/CampaignRepository.java
  src/main/java/com/lokoko/domain/campaign/exception/ErrorMessage.java
  src/main/java/com/lokoko/domain/image/domain/entity/CampaignImage.java
Labels: ✨ Feature

#201 [LCO-18] 구글 소셜 로그인 구현
  src/main/java/com/lokoko/LokokoApplication.java
  src/main/java/com/lokoko/domain/brand/domain/entity/Brand.java
  src/main/java/com/lokoko/domain/brand/domain/repository/BrandRepository.java
  src/main/java/com/lokoko/domain/creator/domain/entity/Creator.java
  src/main/java/com/lokoko/domain/creator/domain/repository/CreatorRepository.java
  src/main/java/com/lokoko/domain/customer/domain/entity/Customer.java
  src/main/java/com/lokoko/domain/customer/domain/repository/CustomerRepository.java
  src/main/java/com/lokoko/domain/user/domain/entity/User.java
  src/main/java/com/lokoko/domain/user/domain/entity/enums/Role.java
  src/main/java/com/lokoko/domain/user/domain/repository/UserRepository.java
  src/main/java/com/lokoko/domain/user/exception/InvalidRoleTransitionException.java
  src/main/java/com/lokoko/global/auth/controller/AuthController.java
  src/main/java/com/lokoko/global/auth/controller/enums/ResponseMessage.java
  src/main/java/com/lokoko/global/auth/entity/Admin.java
  src/main/java/com/lokoko/global/auth/entity/enums/OauthLoginStatus.java
  src/main/java/com/lokoko/global/auth/exception/ErrorMessage.java
  src/main/java/com/lokoko/global/auth/exception/InvalidRoleException.java
  src/main/java/com/lokoko/global/auth/exception/RoleChangeNotAllowedException.java
  src/main/java/com/lokoko/global/auth/exception/UserRoleAlreadyExistException.java
  src/main/java/com/lokoko/global/auth/google/GoogleOAuthClient.java
  src/main/java/com/lokoko/global/auth/google/GoogleProperties.java
  src/main/java/com/lokoko/global/auth/google/dto/GoogleLoginResponse.java
  src/main/java/com/lokoko/global/auth/google/dto/GoogleProfileDto.java
  src/main/java/com/lokoko/global/auth/google/dto/GoogleTokenDto.java
  src/main/java/com/lokoko/global/auth/google/dto/RoleUpdateRequest.java
  src/main/java/com/lokoko/global/auth/google/dto/RoleUpdateResponse.java
  src/main/java/com/lokoko/global/auth/jwt/dto/LoginResponse.java
  src/main/java/com/lokoko/global/auth/service/AuthService.java
  src/main/java/com/lokoko/global/config/WebClientConfig.java
  src/main/java/com/lokoko/global/utils/GoogleConstants.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: ✨ Feature

#216 [FEAT] #216 브랜드/크리에이터 추가 정보 입력 API 및 회원 가입 로직 마무리
  src/main/java/com/lokoko/domain/brand/api/BrandController.java
  src/main/java/com/lokoko/domain/brand/api/dto/request/BrandInfoUpdateRequest.java
  src/main/java/com/lokoko/domain/brand/api/message/ResponseMessage.java
  src/main/java/com/lokoko/domain/brand/application/BrandService.java
  src/main/java/com/lokoko/domain/brand/domain/entity/Brand.java
  src/main/java/com/lokoko/domain/brand/exception/BrandNotFoundException.java
  src/main/java/com/lokoko/domain/brand/exception/ErrorMessage.java
  src/main/java/com/lokoko/domain/creator/api/CreatorController.java
  src/main/java/com/lokoko/domain/creator/api/dto/request/CreatorIdCheckRequest.java
  src/main/java/com/lokoko/domain/creator/api/dto/request/CreatorInfoUpdateRequest.java
  src/main/java/com/lokoko/domain/creator/api/dto/response/CreatorInfoResponse.java
  src/main/java/com/lokoko/domain/creator/api/dto/response/CreatorRegisterCompleteResponse.java
  src/main/java/com/lokoko/domain/creator/api/dto/response/CreatorSnsConnectedResponse.java
  src/main/java/com/lokoko/domain/creator/api/message/ResponseMessage.java
  src/main/java/com/lokoko/domain/creator/application/mapper/CreatorMapper.java
  src/main/java/com/lokoko/domain/creator/application/service/CreatorGetService.java
  src/main/java/com/lokoko/domain/creator/application/service/CreatorUpdateService.java
  src/main/java/com/lokoko/domain/creator/application/service/CreatorUsecase.java
  src/main/java/com/lokoko/domain/creator/domain/entity/Creator.java
  src/main/java/com/lokoko/domain/creator/domain/entity/enums/ContentLanguage.java
  src/main/java/com/lokoko/domain/creator/domain/entity/enums/CreatorType.java
  src/main/java/com/lokoko/domain/creator/domain/repository/CreatorRepository.java
  src/main/java/com/lokoko/domain/creator/exception/CreatorIdAlreadyExistsException.java
  src/main/java/com/lokoko/domain/creator/exception/CreatorInfoNotCompletedException.java
  src/main/java/com/lokoko/domain/creator/exception/CreatorNotFoundException.java
  src/main/java/com/lokoko/domain/creator/exception/ErrorMessage.java
  src/main/java/com/lokoko/domain/creator/exception/NotCreatorRoleException.java
  src/main/java/com/lokoko/domain/creator/exception/SnsNotConnectedException.java
  src/main/java/com/lokoko/global/auth/entity/enums/OauthLoginStatus.java
  src/main/java/com/lokoko/global/auth/jwt/utils/JwtProvider.java
  src/main/java/com/lokoko/global/auth/service/AuthService.java
Labels: ✨ Feature

#219 [Feat] #219 크리에이터 관련 추가 API 구현
  src/main/java/com/lokoko/domain/campaign/api/CampaignController.java
  src/main/java/com/lokoko/domain/campaign/api/dto/response/CampaignParticipatedResponse.java
  src/main/java/com/lokoko/domain/campaign/application/mapper/CampaignMapper.java
  src/main/java/com/lokoko/domain/campaign/application/service/CampaignGetService.java
  src/main/java/com/lokoko/domain/campaign/application/service/CampaignStatusManager.java
  src/main/java/com/lokoko/domain/campaign/domain/entity/enums/ParticipationStatus.java
  src/main/java/com/lokoko/domain/campaign/domain/repository/CampaignRepository.java
  src/main/java/com/lokoko/domain/campaign/domain/repository/CreatorCampaignRepository.java
  src/main/java/com/lokoko/domain/campaignReview/api/CampaignReviewController.java
  src/main/java/com/lokoko/domain/campaignReview/api/dto/request/FirstReviewUploadRequest.java
  src/main/java/com/lokoko/domain/campaignReview/api/dto/response/ReviewUploadResponse.java
  src/main/java/com/lokoko/domain/campaignReview/api/message/ResponseMessage.java
  src/main/java/com/lokoko/domain/campaignReview/application/mapper/CampaignReviewMapper.java
  src/main/java/com/lokoko/domain/campaignReview/application/service/CampaignReviewGetService.java
  src/main/java/com/lokoko/domain/campaignReview/application/service/CreatorCampaignUpdateService.java
  src/main/java/com/lokoko/domain/campaignReview/application/usecase/CampaignReviewUsecase.java
  src/main/java/com/lokoko/domain/campaignReview/domain/entity/CampaignReview.java
  src/main/java/com/lokoko/domain/creator/api/CreatorController.java
  src/main/java/com/lokoko/domain/creator/api/dto/response/CreatorAddressInfo.java
  src/main/java/com/lokoko/domain/creator/api/dto/response/CreatorBasicInfo.java
  src/main/java/com/lokoko/domain/creator/api/dto/response/CreatorContactInfo.java
  src/main/java/com/lokoko/domain/creator/api/dto/response/CreatorFaceInfo.java
  src/main/java/com/lokoko/domain/creator/api/dto/response/CreatorMyCampaignListResponse.java
  src/main/java/com/lokoko/domain/creator/api/dto/response/CreatorMyCampaignResponse.java
  src/main/java/com/lokoko/domain/creator/api/dto/response/CreatorMyPageResponse.java
  src/main/java/com/lokoko/domain/creator/api/message/ResponseMessage.java
  src/main/java/com/lokoko/domain/creator/application/service/CreatorGetService.java
  src/main/java/com/lokoko/domain/creator/application/service/CreatorUpdateService.java
  src/main/java/com/lokoko/domain/creator/application/service/CreatorUsecase.java
  src/main/java/com/lokoko/domain/creator/domain/repository/CreatorRepository.java
  src/main/java/com/lokoko/domain/creatorCampaign/api/CreatorCampaignController.java
  src/main/java/com/lokoko/domain/creatorCampaign/api/message/ResponseMessage.java
  src/main/java/com/lokoko/domain/creatorCampaign/application/mapper/CreatorCampaignMapper.java
  src/main/java/com/lokoko/domain/creatorCampaign/application/service/CreatorCampaignGetService.java
  src/main/java/com/lokoko/domain/creatorCampaign/application/service/CreatorCampaignSaveService.java
  src/main/java/com/lokoko/domain/creatorCampaign/application/usecase/CreatorCampaignUsecase.java
  src/main/java/com/lokoko/domain/creatorCampaign/domain/entity/CreatorCampaign.java
  src/main/java/com/lokoko/domain/creatorCampaign/domain/enums/ParticipationStatus.java
  src/main/java/com/lokoko/domain/creatorCampaign/domain/repository/CreatorCampaignRepository.java
  src/main/java/com/lokoko/domain/creatorCampaign/exception/AlreadyParticipatedCampaignException.java
  src/main/java/com/lokoko/domain/creatorCampaign/exception/CampaignNotRecruitingException.java
  src/main/java/com/lokoko/domain/creatorCampaign/exception/CampaignNotStartedException.java
  src/main/java/com/lokoko/domain/creatorCampaign/exception/CampaignRecruitmentFullException.java
  src/main/java/com/lokoko/domain/creatorCampaign/exception/ErrorMessage.java
Labels: 🔨 Refactor, ✨ Feature

#236 [CHORE] #236 LangueFilter 변경
  src/main/java/com/lokoko/domain/campaign/domain/entity/enums/LanguageFilter.java
Labels: 🔨 Refactor

#229 [Feat] #229 브랜드 마이페이지 캠페인 리스트 조회 & 브랜드 프로필 및 통계 정보 조회 & 임시저장 캠페인 조회 API 구현
  src/main/java/com/lokoko/domain/brand/api/BrandController.java
  src/main/java/com/lokoko/domain/brand/api/dto/response/BrandMyCampaignListResponse.java
  src/main/java/com/lokoko/domain/brand/api/dto/response/BrandMyCampaignResponse.java
  src/main/java/com/lokoko/domain/brand/api/dto/response/BrandProfileAndStatisticsResponse.java
  src/main/java/com/lokoko/domain/brand/api/message/ResponseMessage.java
  src/main/java/com/lokoko/domain/brand/application/BrandService.java
  src/main/java/com/lokoko/domain/campaign/api/dto/response/CampaignBasicResponse.java
  src/main/java/com/lokoko/domain/campaign/api/dto/response/CampaignCreateResponse.java
  src/main/java/com/lokoko/domain/campaign/api/dto/response/CampaignImageResponse.java
  src/main/java/com/lokoko/domain/campaign/api/message/ResponseMessage.java
  src/main/java/com/lokoko/domain/campaign/application/service/CampaignGetService.java
  src/main/java/com/lokoko/domain/campaign/application/service/CampaignService.java
  src/main/java/com/lokoko/domain/campaign/domain/entity/Campaign.java
  src/main/java/com/lokoko/domain/campaign/domain/entity/enums/CampaignStatusFilter.java
  src/main/java/com/lokoko/domain/campaign/domain/repository/CampaignRepository.java
  src/main/java/com/lokoko/domain/campaign/domain/repository/CampaignRepositoryCustom.java
  src/main/java/com/lokoko/domain/campaign/domain/repository/CampaignRepositoryImpl.java
Labels: ✨ Feature

#233 [Feat] #233 크리에이터 승인 API & 캠페인 목록 간단 조회 API & 캠페인 지원자 리스트 조회 API
  src/main/java/com/lokoko/domain/brand/api/BrandController.java
  src/main/java/com/lokoko/domain/brand/api/dto/request/CreatorApproveRequest.java
  src/main/java/com/lokoko/domain/brand/api/dto/response/BrandMyCampaignInfoListResponse.java
  src/main/java/com/lokoko/domain/brand/api/dto/response/BrandMyCampaignInfoResponse.java
  src/main/java/com/lokoko/domain/brand/api/dto/response/CampaignApplicantListResponse.java
  src/main/java/com/lokoko/domain/brand/api/dto/response/CampaignApplicantResponse.java
  src/main/java/com/lokoko/domain/brand/api/dto/response/CreatorApprovedResponse.java
  src/main/java/com/lokoko/domain/brand/api/message/ResponseMessage.java
  src/main/java/com/lokoko/domain/campaign/application/service/CampaignGetService.java
  src/main/java/com/lokoko/domain/campaign/application/service/CampaignService.java
  src/main/java/com/lokoko/domain/campaign/domain/repository/CampaignRepository.java
  src/main/java/com/lokoko/domain/campaign/domain/repository/CampaignRepositoryCustom.java
  src/main/java/com/lokoko/domain/campaign/domain/repository/CampaignRepositoryImpl.java
  src/main/java/com/lokoko/domain/campaign/exception/CampaignApplicantBulkUpdateException.java
  src/main/java/com/lokoko/domain/campaign/exception/CampaignCapacityExceedException.java
  src/main/java/com/lokoko/domain/campaign/exception/ErrorMessage.java
  src/main/java/com/lokoko/domain/campaign/exception/NoApplicableCreatorsException.java
  src/main/java/com/lokoko/domain/creatorCampaign/domain/enums/ParticipationStatus.java
  src/main/java/com/lokoko/domain/creatorCampaign/domain/repository/CreatorCampaignRepository.java
  src/main/java/com/lokoko/domain/creatorCampaign/domain/repository/CreatorCampaignRepositoryCustom.java
  src/main/java/com/lokoko/domain/creatorCampaign/domain/repository/CreatorCampaignRepositoryImpl.java
  src/main/java/com/lokoko/domain/creatorSocialStats/domain/entity/CreatorSocialStats.java
Labels: ✨ Feature

#243 [CHORE] #243 : 틱톡 PermitUrl 변경
  src/main/java/com/lokoko/global/config/PermitUrlConfig.java
Labels: 🔨 Refactor

#247 Feat #247 크리에이터 프로필 사진 presign url 발급 api
  src/main/java/com/lokoko/domain/creator/api/CreatorController.java
  src/main/java/com/lokoko/domain/creator/api/dto/request/CreatorMyPageUpdateRequest.java
  src/main/java/com/lokoko/domain/creator/api/dto/request/CreatorProfileImageRequest.java
  src/main/java/com/lokoko/domain/creator/api/dto/response/CreatorBasicInfo.java
  src/main/java/com/lokoko/domain/creator/api/dto/response/CreatorProfileImageResponse.java
  src/main/java/com/lokoko/domain/creator/api/message/ResponseMessage.java
  src/main/java/com/lokoko/domain/creator/application/mapper/CreatorMapper.java
  src/main/java/com/lokoko/domain/creator/application/service/CreatorUpdateService.java
  src/main/java/com/lokoko/domain/creator/application/service/CreatorUsecase.java
Labels: 🔨 Refactor, ✨ Feature

#263 [REFACTOR] #263 Customer 와 Creator 의 SNS 연동 확인 로직을 통일
  src/main/java/com/lokoko/domain/creator/application/mapper/CreatorMapper.java
  src/main/java/com/lokoko/domain/creator/application/service/CreatorUsecase.java
  src/main/java/com/lokoko/domain/creator/domain/entity/Creator.java
  src/main/java/com/lokoko/global/auth/service/AuthService.java
Labels: 🔨 Refactor

#239 [REFACTOR] #239 캠페인 상세조회를 비로그인 유저 / CUSTOMER / BRAND / ADMIN 도 가능하도록 변경
  src/main/java/com/lokoko/domain/campaign/api/CampaignController.java
  src/main/java/com/lokoko/domain/campaign/api/dto/response/CampaignDetailResponse.java
  src/main/java/com/lokoko/domain/campaign/application/service/CampaignGetService.java
  src/main/java/com/lokoko/domain/campaign/application/service/CampaignStatusManager.java
  src/main/java/com/lokoko/domain/campaign/domain/entity/enums/CampaignDetailPageStatus.java
Labels: 🔨 Refactor

#260 [FEAT] #260 브랜드 마이페이지 캠페인 대시보드 API 구현
  src/main/java/com/lokoko/domain/brand/api/BrandController.java
  src/main/java/com/lokoko/domain/brand/api/dto/response/BrandDashboardCampaignListResponse.java
  src/main/java/com/lokoko/domain/brand/api/dto/response/BrandDashboardCampaignResponse.java
  src/main/java/com/lokoko/domain/brand/api/message/ResponseMessage.java
  src/main/java/com/lokoko/domain/campaign/application/service/CampaignGetService.java
  src/main/java/com/lokoko/domain/campaign/domain/repository/CampaignRepositoryCustom.java
  src/main/java/com/lokoko/domain/campaign/domain/repository/CampaignRepositoryImpl.java
Labels: ✨ Feature

#278 [REFACTOR] #278 : CampaignApplicantResponse 응답 구조 변경
  src/main/java/com/lokoko/domain/brand/api/dto/response/CampaignApplicantResponse.java
  src/main/java/com/lokoko/domain/creatorCampaign/domain/repository/CreatorCampaignRepositoryImpl.java
Labels: 🔨 Refactor

#276 [REFACTOR] #276 : SocialClip 엔티티의 필드 수정
  src/main/java/com/lokoko/domain/media/socialclip/domain/SocialClip.java
Labels: 🔨 Refactor

#283 [Refactor] #283 크리에이터 마이페이지- 내가 참여한/참여중인 캠페인 조회 API 의 응답 구조 수정
  src/main/java/com/lokoko/domain/creator/api/CreatorController.java
  src/main/java/com/lokoko/domain/creator/api/dto/response/CreatorBasicInfo.java
  src/main/java/com/lokoko/domain/creator/api/dto/response/CreatorMyCampaignListResponse.java
  src/main/java/com/lokoko/domain/creator/api/dto/response/CreatorMyCampaignResponse.java
  src/main/java/com/lokoko/domain/creator/application/service/CreatorUsecase.java
  src/main/java/com/lokoko/domain/creatorCampaign/application/mapper/CreatorCampaignMapper.java
Labels: 🔨 Refactor

#288 [REFACTOR] #288 상태 관리 로직 변경 및 크리에이터 리뷰 관련 로직 리팩토링
  src/main/java/com/lokoko/domain/campaign/api/dto/response/CampaignParticipatedResponse.java
  src/main/java/com/lokoko/domain/campaign/application/mapper/CampaignMapper.java
  src/main/java/com/lokoko/domain/campaign/application/service/CampaignStatusManager.java
  src/main/java/com/lokoko/domain/campaignReview/api/CampaignReviewController.java
  src/main/java/com/lokoko/domain/campaignReview/application/service/CampaignReviewGetService.java
  src/main/java/com/lokoko/domain/campaignReview/application/service/CampaignReviewStatusManager.java
  src/main/java/com/lokoko/domain/campaignReview/application/service/CreatorCampaignUpdateService.java
  src/main/java/com/lokoko/domain/campaignReview/application/usecase/CampaignReviewUsecase.java
  src/main/java/com/lokoko/domain/campaignReview/domain/entity/CampaignReview.java
  src/main/java/com/lokoko/domain/creator/api/dto/response/CreatorBasicInfo.java
  src/main/java/com/lokoko/domain/creator/api/dto/response/CreatorMyCampaignResponse.java
  src/main/java/com/lokoko/domain/creator/api/dto/response/NextAction.java
  src/main/java/com/lokoko/domain/creator/application/mapper/CreatorMapper.java
  src/main/java/com/lokoko/domain/creator/util/CampaignStatusMapper.java
  src/main/java/com/lokoko/domain/creatorCampaign/application/mapper/CreatorCampaignMapper.java
  src/main/java/com/lokoko/domain/creatorCampaign/application/service/CreatorCampaignGetService.java
  src/main/java/com/lokoko/domain/creatorCampaign/domain/enums/ParticipationStatus.java
  src/main/java/com/lokoko/domain/creatorCampaign/domain/repository/CreatorCampaignRepositoryImpl.java
  src/main/java/com/lokoko/global/config/PermitUrlConfig.java
Labels: 🔨 Refactor, ✨ Feature

#290 [REFACTOR] #290 : 캠페인 대표 이미지 조회 코드 추가
  src/main/java/com/lokoko/domain/creator/api/dto/response/CreatorMyCampaignResponse.java
  src/main/java/com/lokoko/domain/creatorCampaign/application/mapper/CreatorCampaignMapper.java
Labels: 🐞 Fix, 🔨 Refactor

#296 [REFACTOR] #296 : CampaignReview 에 유니크 제약 조건 추가
  src/main/java/com/lokoko/domain/campaignReview/domain/entity/CampaignReview.java
Labels: 🔨 Refactor

#300 [FIX] #300 인스타그램 / 틱톡 OAuth 연동 방식 변경
  src/main/java/com/lokoko/global/auth/provider/controller/SnsConnectionController.java
Labels: 🐞 Fix

#298 [FEAT] #298 : 크리에이터 최종 제출 리뷰 조회 API 구현
  src/main/java/com/lokoko/domain/campaign/application/service/CampaignStatusManager.java
  src/main/java/com/lokoko/domain/campaignReview/api/CampaignReviewController.java
  src/main/java/com/lokoko/domain/campaignReview/api/dto/response/CompletedReviewResponse.java
  src/main/java/com/lokoko/domain/campaignReview/api/message/ResponseMessage.java
  src/main/java/com/lokoko/domain/campaignReview/application/usecase/CampaignReviewUsecase.java
  src/main/java/com/lokoko/domain/creatorCampaign/domain/repository/CreatorCampaignRepository.java
Labels: ✨ Feature

#303 [FIX] #303 : servlet response 를 JAVAX - > jakarta 로 변경
  src/main/java/com/lokoko/global/auth/provider/controller/SnsConnectionController.java
Labels: 🐞 Fix

#314 [FIX] #313 CaddyFile 에 www 주소 추가
  .github/workflows/prod.yml
  src/main/java/com/lokoko/global/config/SecurityConfig.java
Labels: 🐞 Fix

#325 [REFACTOR] #325 틱톡 연결 API ENDPOINT 변경
  src/main/java/com/lokoko/global/auth/provider/controller/SnsConnectionController.java
Labels: 🔨 Refactor
