Repository LO-CO-CO/LOCOCO-SERVER, pull requests merged in 2025-07, with the labels that each got.

#29 [Refactor] #29 라인 소셜 로그인 고도화
  build.gradle
  src/main/java/com/lokoko/domain/user/entity/User.java
  src/main/java/com/lokoko/global/auth/annotation/CurrentUserResolver.java
  src/main/java/com/lokoko/global/auth/controller/AuthController.java
  src/main/java/com/lokoko/global/auth/controller/enums/ResponseMessage.java
  src/main/java/com/lokoko/global/auth/jwt/dto/GenerateTokenDto.java
  src/main/java/com/lokoko/global/auth/jwt/dto/JwtTokenDto.java
  src/main/java/com/lokoko/global/auth/jwt/dto/LoginDto.java
  src/main/java/com/lokoko/global/auth/jwt/exception/CookieNotFoundException.java
  src/main/java/com/lokoko/global/auth/jwt/exception/RefreshTokenNotFoundException.java
  src/main/java/com/lokoko/global/auth/jwt/exception/TokenExpiredException.java
  src/main/java/com/lokoko/global/auth/jwt/exception/TokenInvalidException.java
  src/main/java/com/lokoko/global/auth/jwt/service/JwtService.java
  src/main/java/com/lokoko/global/auth/jwt/utils/CookieUtil.java
  src/main/java/com/lokoko/global/auth/jwt/utils/JwtExtractor.java
  src/main/java/com/lokoko/global/auth/jwt/utils/JwtProvider.java
  src/main/java/com/lokoko/global/auth/line/dto/LineLoginResponse.java
  src/main/java/com/lokoko/global/auth/line/dto/LineProfileResponse.java
  src/main/java/com/lokoko/global/auth/resolver/CurrentUserResolver.java
  src/main/java/com/lokoko/global/auth/service/AuthService.java
  src/main/java/com/lokoko/global/config/RedisConfig.java
  src/main/java/com/lokoko/global/config/WebMvcConfig.java
  src/main/java/com/lokoko/global/utils/LineConstants.java
  src/main/java/com/lokoko/global/utils/RedisUtil.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: 🔨 Refactor, ✨ Feature

#34 [Refactor] #34 카테고리 별 상품 검색 로직 수정
  src/main/java/com/lokoko/domain/product/controller/ProductController.java
  src/main/java/com/lokoko/domain/product/dto/ProductResponse.java
  src/main/java/com/lokoko/domain/product/dto/ProductSummary.java
  src/main/java/com/lokoko/domain/product/exception/ErrorMessage.java
  src/main/java/com/lokoko/domain/product/exception/MiddleCategoryNotFoundException.java
  src/main/java/com/lokoko/domain/product/repository/ProductRepository.java
  src/main/java/com/lokoko/domain/product/service/ProductService.java
  src/main/java/com/lokoko/domain/review/entity/Review.java
  src/main/java/com/lokoko/domain/review/repository/ReviewRepository.java
Labels: 🔨 Refactor, ✨ Feature

#37 [CHORE] #37 querydsl 기본세팅
  .gitignore
  build.gradle
  src/main/java/com/lokoko/global/config/QueryDslConfig.java
Labels: ⚙ Setting, ✨ Feature

#43 [Feat] #43 상품 신제품 조회, 상세조회 api 구현
  src/main/java/com/lokoko/domain/product/controller/ProductController.java
  src/main/java/com/lokoko/domain/product/controller/enums/ResponseMessage.java
  src/main/java/com/lokoko/domain/product/dto/CategoryNewProductResponse.java
  src/main/java/com/lokoko/domain/product/dto/CategoryProductResponse.java
  src/main/java/com/lokoko/domain/product/dto/ProductDetailResponse.java
  src/main/java/com/lokoko/domain/product/dto/ProductDetailYoutubeResponse.java
  src/main/java/com/lokoko/domain/product/dto/ProductResponse.java
  src/main/java/com/lokoko/domain/product/repository/ProductOptionRepository.java
  src/main/java/com/lokoko/domain/product/repository/ProductRepository.java
  src/main/java/com/lokoko/domain/product/service/ProductReadService.java
  src/main/java/com/lokoko/domain/product/service/ProductService.java
  src/main/java/com/lokoko/domain/review/entity/Review.java
  src/main/java/com/lokoko/domain/review/repository/ReviewRepository.java
Labels: 🔨 Refactor, ✨ Feature

#54 [Refactor] #54 카테고리 요청 파라미터 enum 형식으로 변경
  src/main/java/com/lokoko/domain/product/controller/ProductController.java
  src/main/java/com/lokoko/domain/product/service/ProductReadService.java
Labels: 🔨 Refactor

#56 [FEAT] #56 카테고리 별 리뷰 검색 기능 추가
  src/main/java/com/lokoko/domain/product/controller/ProductController.java
  src/main/java/com/lokoko/domain/product/controller/enums/ResponseMessage.java
  src/main/java/com/lokoko/domain/review/dto/ImageReviewListResponse.java
  src/main/java/com/lokoko/domain/review/dto/ImageReviewResponse.java
  src/main/java/com/lokoko/domain/review/dto/VideoReviewListResponse.java
  src/main/java/com/lokoko/domain/review/dto/VideoReviewResponse.java
  src/main/java/com/lokoko/domain/review/repository/ReviewRepository.java
  src/main/java/com/lokoko/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/lokoko/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/lokoko/domain/review/service/ReviewReadService.java
  src/main/java/com/lokoko/global/common/entity/MediaType.java
  src/main/java/com/lokoko/global/common/entity/SearchType.java
Labels: ✨ Feature

#57 [FEAT] #57 영수증 사진 업로드 API
  src/main/java/com/lokoko/domain/image/controller/enums/ResponseMessage.java
  src/main/java/com/lokoko/domain/image/exception/ErrorMessage.java
  src/main/java/com/lokoko/domain/image/exception/FileTypeNotSupportedException.java
  src/main/java/com/lokoko/domain/review/controller/ReviewController.java
  src/main/java/com/lokoko/domain/review/controller/enums/ResponseMessage.java
  src/main/java/com/lokoko/domain/review/dto/request/ReviewReceiptRequest.java
  src/main/java/com/lokoko/domain/review/dto/response/ReviewReceiptResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/ReviewReceiptUrl.java
  src/main/java/com/lokoko/domain/review/exception/ErrorMessage.java
  src/main/java/com/lokoko/domain/review/exception/InvalidMediaTypeException.java
  src/main/java/com/lokoko/domain/review/service/ReviewService.java
  src/main/java/com/lokoko/domain/review/utils/AllowedMediaType.java
  src/main/java/com/lokoko/global/common/dto/PresignedUrlResponse.java
  src/main/java/com/lokoko/global/common/service/S3Service.java
  src/main/java/com/lokoko/global/config/S3Config.java
Labels: ✨ Feature

#59 [Feat] #59 상품명 또는 브랜드명으로 리뷰 검색 기능 추가
  src/main/java/com/lokoko/domain/product/controller/ProductController.java
  src/main/java/com/lokoko/domain/product/controller/enums/ResponseMessage.java
  src/main/java/com/lokoko/domain/product/dto/ProductDetailResponse.java
  src/main/java/com/lokoko/domain/product/dto/ProductSearchRequest.java
  src/main/java/com/lokoko/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/lokoko/domain/product/service/ProductReadService.java
  src/main/java/com/lokoko/domain/review/dto/KeywordImageReviewListResponse.java
  src/main/java/com/lokoko/domain/review/dto/KeywordVideoReviewListResponse.java
  src/main/java/com/lokoko/domain/review/dto/ReviewListResponse.java
  src/main/java/com/lokoko/domain/review/exception/ErrorMessage.java
  src/main/java/com/lokoko/domain/review/exception/MissingMediaTypeException.java
  src/main/java/com/lokoko/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/lokoko/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/lokoko/domain/review/service/ReviewReadService.java
Labels: ✨ Feature

#68 [FEAT] #61 리뷰 작성, 리뷰 영상/사진 업로드 API
  src/main/java/com/lokoko/domain/image/entity/ReviewImage.java
  src/main/java/com/lokoko/domain/product/controller/ProductController.java
  src/main/java/com/lokoko/domain/product/dto/request/CrawlRequest.java
  src/main/java/com/lokoko/domain/product/dto/response/CategoryNewProductResponse.java
  src/main/java/com/lokoko/domain/product/dto/response/CategoryPopularProductResponse.java
  src/main/java/com/lokoko/domain/product/dto/response/CategoryProductPageResponse.java
  src/main/java/com/lokoko/domain/product/dto/response/CategoryProductResponse.java
  src/main/java/com/lokoko/domain/product/dto/response/CrawlResponse.java
  src/main/java/com/lokoko/domain/product/dto/response/NameBrandProductResponse.java
  src/main/java/com/lokoko/domain/product/dto/response/ProductDetailResponse.java
  src/main/java/com/lokoko/domain/product/dto/response/ProductDetailYoutubeResponse.java
  src/main/java/com/lokoko/domain/product/dto/response/ProductOptionResponse.java
  src/main/java/com/lokoko/domain/product/dto/response/ProductResponse.java
  src/main/java/com/lokoko/domain/product/dto/response/ProductSummary.java
  src/main/java/com/lokoko/domain/product/exception/ErrorMessage.java
  src/main/java/com/lokoko/domain/product/exception/ProductOptionMismatchException.java
  src/main/java/com/lokoko/domain/product/exception/ProductOptionNotFoundException.java
  src/main/java/com/lokoko/domain/product/repository/ProductRepository.java
  src/main/java/com/lokoko/domain/product/service/ProductReadService.java
  src/main/java/com/lokoko/domain/product/service/ProductService.java
  src/main/java/com/lokoko/domain/review/controller/ReviewController.java
  src/main/java/com/lokoko/domain/review/controller/enums/ResponseMessage.java
  src/main/java/com/lokoko/domain/review/dto/VideoReviewListResponse.java
  src/main/java/com/lokoko/domain/review/dto/request/ReviewMediaRequest.java
  src/main/java/com/lokoko/domain/review/dto/request/ReviewRequest.java
  src/main/java/com/lokoko/domain/review/dto/response/ImageReviewListResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/ImageReviewResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/KeywordImageReviewListResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/KeywordVideoReviewListResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/ReviewListResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/ReviewMediaResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/ReviewMediaUrl.java
  src/main/java/com/lokoko/domain/review/dto/response/ReviewResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/VideoReviewListResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/VideoReviewResponse.java
  src/main/java/com/lokoko/domain/review/entity/Review.java
  src/main/java/com/lokoko/domain/review/exception/ErrorMessage.java
  src/main/java/com/lokoko/domain/review/exception/PresignedUrlParsingException.java
  src/main/java/com/lokoko/domain/review/exception/ReceiptImageCountingException.java
  src/main/java/com/lokoko/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/lokoko/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/lokoko/domain/review/service/ReviewReadService.java
  src/main/java/com/lokoko/domain/review/service/ReviewService.java
  src/main/java/com/lokoko/domain/review/utils/S3UrlParser.java
  src/main/java/com/lokoko/domain/user/exception/ErrorMessage.java
  src/main/java/com/lokoko/domain/user/exception/UserNotFoundException.java
  src/main/java/com/lokoko/domain/video/entity/ReviewVideo.java
  src/main/java/com/lokoko/domain/youtube/controller/YoutubeController.java
  src/main/java/com/lokoko/global/common/entity/MediaFile.java
Labels: ✨ Feature

#67 [FEAT] #67 어드민 리뷰 삭제 API 구현
  src/main/java/com/lokoko/domain/image/repository/ReceiptImageRepository.java
  src/main/java/com/lokoko/domain/image/repository/ReviewImageRepository.java
  src/main/java/com/lokoko/domain/review/exception/ErrorMessage.java
  src/main/java/com/lokoko/domain/review/exception/ReviewNotFoundException.java
  src/main/java/com/lokoko/domain/review/service/ReviewService.java
  src/main/java/com/lokoko/domain/user/admin/controller/AdminController.java
  src/main/java/com/lokoko/domain/user/admin/controller/enums/ResponseMessage.java
  src/main/java/com/lokoko/domain/user/admin/service/AdminReviewService.java
  src/main/java/com/lokoko/domain/user/exception/ErrorMessage.java
  src/main/java/com/lokoko/domain/user/exception/UserNotFoundException.java
  src/main/java/com/lokoko/domain/video/repository/ReviewVideoRepository.java
  src/main/java/com/lokoko/global/auth/exception/AdminPermissionRequiredException.java
  src/main/java/com/lokoko/global/auth/exception/ErrorMessage.java
  src/main/java/com/lokoko/global/utils/AdminValidator.java
  src/main/java/com/lokoko/global/utils/AllowedMediaType.java
  src/main/java/com/lokoko/global/utils/RatingConverter.java
  src/main/java/com/lokoko/global/utils/S3UrlParser.java
Labels: ✨ Feature

#76 [REFACTOR] #76 테스트용 토큰 발급 API 구현 및 isLiked 필드 추가반환 및 점수대별 퍼센트 추가 반환
  src/main/java/com/lokoko/domain/like/controller/ReviewLikeController.java
  src/main/java/com/lokoko/domain/like/repository/ProductLikeRepository.java
  src/main/java/com/lokoko/domain/like/service/ProductLikeService.java
  src/main/java/com/lokoko/domain/product/dto/response/ProductDetailResponse.java
  src/main/java/com/lokoko/domain/product/dto/response/ScorePercent.java
  src/main/java/com/lokoko/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/lokoko/domain/product/service/ProductReadService.java
  src/main/java/com/lokoko/domain/product/service/ProductService.java
  src/main/java/com/lokoko/domain/review/dto/request/RatingCount.java
  src/main/java/com/lokoko/domain/review/repository/ReviewRepository.java
  src/main/java/com/lokoko/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/lokoko/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/lokoko/global/auth/controller/AuthController.java
  src/main/java/com/lokoko/global/auth/controller/JwtLoginResponse.java
  src/main/java/com/lokoko/global/auth/controller/TestLoginRequest.java
  src/main/java/com/lokoko/global/auth/jwt/dto/JwtTokenDto.java
  src/main/java/com/lokoko/global/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/lokoko/global/auth/jwt/service/JwtService.java
  src/main/java/com/lokoko/global/auth/jwt/utils/JwtProvider.java
  src/main/java/com/lokoko/global/config/SecurityConfig.java
  src/main/java/com/lokoko/global/config/swagger/SwaggerConfig.java
Labels: 🔨 Refactor, ✨ Feature

#71 [Feat] #71 메인페이지에서 상품 리뷰
  src/main/java/com/lokoko/domain/image/repository/ReviewImageRepository.java
  src/main/java/com/lokoko/domain/image/repository/ReviewImageRepositoryCustom.java
  src/main/java/com/lokoko/domain/image/repository/ReviewImageRepositoryImpl.java
  src/main/java/com/lokoko/domain/review/controller/ReviewController.java
  src/main/java/com/lokoko/domain/review/controller/enums/ResponseMessage.java
  src/main/java/com/lokoko/domain/review/dto/response/MainImageReview.java
  src/main/java/com/lokoko/domain/review/dto/response/MainImageReviewResponse.java
  src/main/java/com/lokoko/domain/review/entity/Review.java
  src/main/java/com/lokoko/domain/review/service/ReviewService.java
Labels: ✨ Feature

#78 [Feat] #78 리뷰 좋아요 기능 구현
  src/main/java/com/lokoko/domain/like/controller/ProductLikeController.java
  src/main/java/com/lokoko/domain/like/controller/ReviewLikeController.java
  src/main/java/com/lokoko/domain/like/controller/enums/ResponseMessage.java
  src/main/java/com/lokoko/domain/like/dto/response/ReviewLikeResponse.java
  src/main/java/com/lokoko/domain/like/dto/response/ToggleLikeResponse.java
  src/main/java/com/lokoko/domain/like/entity/ReviewLike.java
  src/main/java/com/lokoko/domain/like/repository/ReviewLikeRepository.java
  src/main/java/com/lokoko/domain/like/service/ReviewLikeService.java
Labels: ✨ Feature

#74 [Feat] #74 비디오 리뷰 조회 API (메인페이지)
  src/main/java/com/lokoko/domain/review/controller/ReviewController.java
  src/main/java/com/lokoko/domain/review/controller/enums/ResponseMessage.java
  src/main/java/com/lokoko/domain/review/dto/response/MainVideoReview.java
  src/main/java/com/lokoko/domain/review/dto/response/MainVideoReviewResponse.java
  src/main/java/com/lokoko/domain/review/service/ReviewService.java
  src/main/java/com/lokoko/domain/user/admin/controller/AdminController.java
  src/main/java/com/lokoko/domain/video/repository/ReviewVideoRepository.java
  src/main/java/com/lokoko/domain/video/repository/ReviewVideoRepositoryCustom.java
  src/main/java/com/lokoko/domain/video/repository/ReviewVideoRepositoryImpl.java
Labels: ✨ Feature

#82 [Feat] #62 제품 상세 페이지에서 사진 리뷰 조회
  src/main/java/com/lokoko/domain/product/controller/ProductController.java
  src/main/java/com/lokoko/domain/review/controller/ReviewController.java
  src/main/java/com/lokoko/domain/review/controller/enums/ResponseMessage.java
  src/main/java/com/lokoko/domain/review/dto/response/ImageReviewProductDetailResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/ImageReviewsProductDetailResponse.java
  src/main/java/com/lokoko/domain/review/entity/Review.java
  src/main/java/com/lokoko/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/lokoko/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/lokoko/domain/review/service/ReviewService.java
Labels: ✨ Feature

#85 MOD #84 : search token 갱신 API 의 @Hidden 해제
  src/main/java/com/lokoko/domain/product/controller/ProductController.java
Labels: 🔨 Refactor

#91 [Feat] #91 어드민용 리뷰 작성 api 구현
  src/main/java/com/lokoko/domain/image/entity/ReviewImage.java
  src/main/java/com/lokoko/domain/review/controller/ReviewController.java
  src/main/java/com/lokoko/domain/review/dto/request/ReviewAdminRequest.java
  src/main/java/com/lokoko/domain/review/entity/Review.java
  src/main/java/com/lokoko/domain/review/service/ReviewService.java
  src/main/java/com/lokoko/global/common/entity/MediaFile.java
  src/main/java/com/lokoko/global/config/PermitUrlConfig.java
Labels: ✨ Feature

#98 [FEAT] #98 사진 및 영상 리뷰 상세조회에서 영수증 조회 기능 추가(어드민)
  src/main/java/com/lokoko/domain/image/repository/ReceiptImageRepository.java
  src/main/java/com/lokoko/domain/review/dto/response/ImageReviewDetailResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/VideoReviewDetailResponse.java
  src/main/java/com/lokoko/domain/review/exception/ErrorMessage.java
  src/main/java/com/lokoko/domain/review/exception/ReceiptNotFoundException.java
  src/main/java/com/lokoko/domain/review/service/ReviewDetailsService.java
Labels: ✨ Feature

#100 Refactor #100 Swagger requiredMode 추가
  src/main/java/com/lokoko/domain/like/dto/response/ReviewLikeResponse.java
  src/main/java/com/lokoko/domain/like/dto/response/ToggleLikeResponse.java
  src/main/java/com/lokoko/domain/product/dto/ProductResponse.java
  src/main/java/com/lokoko/domain/product/dto/response/CategoryNewProductResponse.java
  src/main/java/com/lokoko/domain/product/dto/response/CategoryPopularProductResponse.java
  src/main/java/com/lokoko/domain/product/dto/response/CategoryProductPageResponse.java
  src/main/java/com/lokoko/domain/product/dto/response/CategoryProductResponse.java
  src/main/java/com/lokoko/domain/product/dto/response/NameBrandProductResponse.java
  src/main/java/com/lokoko/domain/product/dto/response/ProductDetailResponse.java
  src/main/java/com/lokoko/domain/product/dto/response/ProductDetailYoutubeResponse.java
  src/main/java/com/lokoko/domain/product/dto/response/ProductMainImageResponse.java
  src/main/java/com/lokoko/domain/product/dto/response/ProductOptionResponse.java
  src/main/java/com/lokoko/domain/product/dto/response/ProductResponse.java
  src/main/java/com/lokoko/domain/product/dto/response/ProductSummary.java
  src/main/java/com/lokoko/domain/product/dto/response/ScorePercent.java
  src/main/java/com/lokoko/domain/product/service/ProductReadService.java
  src/main/java/com/lokoko/domain/product/service/ProductService.java
  src/main/java/com/lokoko/domain/review/dto/response/ImageReviewDetailResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/ImageReviewListResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/ImageReviewProductDetailResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/ImageReviewResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/ImageReviewsProductDetailResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/KeywordImageReviewListResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/KeywordVideoReviewListResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/MainImageReview.java
  src/main/java/com/lokoko/domain/review/dto/response/MainImageReviewResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/MainVideoReview.java
  src/main/java/com/lokoko/domain/review/dto/response/MainVideoReviewResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/ReviewListResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/ReviewMediaResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/ReviewMediaUrl.java
  src/main/java/com/lokoko/domain/review/dto/response/ReviewReceiptResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/ReviewReceiptUrl.java
  src/main/java/com/lokoko/domain/review/dto/response/ReviewResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/VideoReviewDetailResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/VideoReviewListResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/VideoReviewProductDetail.java
  src/main/java/com/lokoko/domain/review/dto/response/VideoReviewProductDetailResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/VideoReviewResponse.java
  src/main/java/com/lokoko/domain/youtube/dto/VideoResponse.java
  src/main/java/com/lokoko/global/auth/controller/AuthController.java
  src/main/java/com/lokoko/global/auth/controller/JwtLoginResponse.java
  src/main/java/com/lokoko/global/auth/jwt/dto/JwtTokenDto.java
  src/main/java/com/lokoko/global/auth/jwt/dto/JwtTokenResponse.java
  src/main/java/com/lokoko/global/auth/jwt/dto/LoginDto.java
  src/main/java/com/lokoko/global/auth/jwt/dto/LoginResponse.java
  src/main/java/com/lokoko/global/auth/jwt/dto/RefreshTokenDto.java
  src/main/java/com/lokoko/global/auth/jwt/service/JwtService.java
  src/main/java/com/lokoko/global/auth/line/LineOAuthClient.java
  src/main/java/com/lokoko/global/auth/line/dto/LineLoginResponse.java
  src/main/java/com/lokoko/global/auth/line/dto/LineProfileDto.java
  src/main/java/com/lokoko/global/auth/line/dto/LineTokenDto.java
  src/main/java/com/lokoko/global/auth/line/dto/LineUserInfoDto.java
  src/main/java/com/lokoko/global/auth/line/dto/LoginUrlResponse.java
  src/main/java/com/lokoko/global/auth/service/AuthService.java
  src/main/java/com/lokoko/global/common/dto/PresignedUrlResponse.java
  src/main/java/com/lokoko/global/common/response/PageableResponse.java
Labels: 🔨 Refactor

#102 [REFACTOR] #102 비로그인 접근 권한 고도화
  src/main/java/com/lokoko/domain/product/service/ProductService.java
  src/main/java/com/lokoko/domain/review/dto/response/ImageReviewDetailResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/VideoReviewDetailResponse.java
  src/main/java/com/lokoko/domain/review/service/ReviewDetailsService.java
  src/main/java/com/lokoko/global/auth/resolver/CurrentUserResolver.java
  src/main/java/com/lokoko/global/config/PermitUrlConfig.java
  src/main/java/com/lokoko/global/config/SecurityConfig.java
Labels: 🔨 Refactor

#113 [FEAT] #113 : 무중단 배포 CI/CD 구축
  .github/workflows/dev.yml
Labels: ✨ Feature

#121 [FIX] #120 제품 상세 페이지에서 유저 리뷰가 없을 때 빈 리스트로 반환하도록 수정
  src/main/java/com/lokoko/domain/review/repository/ReviewRepositoryImpl.java
Labels: 🐞 Fix

#123 [REFACTOR] #123 이미지, 영상 리뷰 업로드 세부로직 수정
  src/main/java/com/lokoko/domain/review/dto/request/ReviewAdminRequest.java
  src/main/java/com/lokoko/domain/review/dto/response/ImageReviewDetailResponse.java
  src/main/java/com/lokoko/domain/review/service/ReviewService.java
Labels: 🔨 Refactor

#126 [FIX] #126 사진/리뷰 상세조회 페이지에서 별점의 return type 을 String 에서 Double 로 변경
  src/main/java/com/lokoko/domain/review/dto/response/ImageReviewDetailResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/VideoReviewDetailResponse.java
Labels: 🐞 Fix

#128 [REFACTOR] #128 : 상품명 / 브랜드명 리뷰 검색 로직 수정
  src/main/java/com/lokoko/domain/review/repository/ReviewRepositoryImpl.java
Labels: 🔨 Refactor

#132 [REFACTOR] #132 사진/영상 리뷰 상세 조회 응답에 productId 추가
  src/main/java/com/lokoko/domain/review/dto/response/ImageReviewDetailResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/VideoReviewDetailResponse.java
Labels: 🔨 Refactor

#134 REFACTOR #134 : 본인의 리뷰 영상에도 좋아요 누를 수 있도록 설정
  src/main/java/com/lokoko/domain/like/service/ReviewLikeService.java
Labels: 🔨 Refactor, ✨ Feature

#138 [FIX] #138 : 어드민 리뷰 삭제 API 에서 userId 를 hidden 으로 수정
  src/main/java/com/lokoko/domain/user/admin/controller/AdminController.java
Labels: 🐞 Fix

#143 [Refactor] #141 : 별점 소수점 반환 형식 수정
  src/main/java/com/lokoko/domain/product/dto/response/ProductDetailResponse.java
  src/main/java/com/lokoko/domain/product/dto/response/ProductMainImageResponse.java
  src/main/java/com/lokoko/domain/product/dto/response/ProductResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/ImageReviewDetailResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/ImageReviewProductDetailResponse.java
  src/main/java/com/lokoko/domain/review/dto/response/VideoReviewDetailResponse.java
Labels: 🔨 Refactor

#156 CHORE #156 분산락 기본 세팅
  build.gradle
  src/main/java/com/lokoko/global/common/annotation/DistributedLock.java
  src/main/java/com/lokoko/global/common/aop/lock/CustomSpringELParser.java
  src/main/java/com/lokoko/global/common/aop/lock/RedissonLockAspect.java
  src/main/java/com/lokoko/global/common/aop/transaction/AopForTransaction.java
  src/main/java/com/lokoko/global/config/redis/RedisConfig.java
  src/main/java/com/lokoko/global/config/redis/RedissonConfig.java
Labels: ⚙ Setting, 🔨 Refactor

#161 [REFACTOR] #161 상품 도메인 비즈니스 로직 개선
  src/main/java/com/lokoko/domain/product/api/ProductController.java
  src/main/java/com/lokoko/domain/product/api/dto/NewProductProjection.java
  src/main/java/com/lokoko/domain/product/api/dto/PopularProductProjection.java
  src/main/java/com/lokoko/domain/product/api/dto/ReviewStats.java
  src/main/java/com/lokoko/domain/product/application/service/ProductImageService.java
  src/main/java/com/lokoko/domain/product/application/service/ProductReadService.java
  src/main/java/com/lokoko/domain/product/application/service/ProductService.java
  src/main/java/com/lokoko/domain/product/application/service/ProductStatsCalculatorService.java
  src/main/java/com/lokoko/domain/product/domain/repository/ProductRepositoryCustom.java
  src/main/java/com/lokoko/domain/product/domain/repository/ProductRepositoryImpl.java
  src/main/java/com/lokoko/domain/product/mapper/ProductMapper.java
Labels: 🔨 Refactor
